name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rust:1.82
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: make build

  test:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: rust:1.82
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: make test

  check-format:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: rust:1.82
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install rustfmt
        run: rustup component add rustfmt

      - name: Verify the source code is formatted
        run: make check-format

  clippy:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: rust:1.82
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install clippy
        run: rustup component add clippy

      - name: Run clippy
        run: make lint
