name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rust:1.82
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: make build

  test:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: rust:1.82
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust components
        run: |
          rustup component add clippy
          rustup component add rustfmt

      # - name: Run clippy
      #   run: make lint

      - name: Verify the source code is formatted
        run: make check-format

      - name: Run tests
        run: make test
